### ISSUE TITLE
[Tracking Issue] Planned MSC support

### ISSUE THREAD

**Issue by MTRNord** [MTRNord/cetirizine#1]
This issue lists MSCs planned to be added or at least considered.

- [ ] [MSC3767](https://github.com/matrix-org/matrix-spec-proposals/pull/3767): Time based notification filtering - For worktime notification presets
- [ ] [MSC3088](https://github.com/matrix-org/matrix-spec-proposals/pull/3088): Room subtyping - For marking rooms as microblogging, allowing for extended richtext editor features
- [ ] [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575): Sliding Sync (aka Sync v3) - If I am going to build a new SDK from scratch, I might as well use this directly. Also, this seems to fit the redux world better.
- [ ] [MSC3964](https://github.com/matrix-org/matrix-spec-proposals/pull/3964): Notifications for room tags - Just seems like a sane thing to implement while I am at it anyway
- [ ] Explicitly opt out of implementing OIDC due to the core issues of the MSCs which seem to be actively ignored
- [ ] Widgets (even considering how bad the spec on it is. aka there being no spec essentially)
- [ ] ...
